### ISSUE TITLE
rpi pico won't upload

### ISSUE THREAD

**Issue by exur00** [sanjay900/Ardwiino#8]
I am using a pico, and when I put it in bootsel before opening guitar-configurator I can select the pico, but it then instantly gets stuck on "Programming Status: Waiting for Reconnection (0.00%)". In the terminal it also prints "Error retrieving serial".
If I ignore the recommendation I don't put the pico in bootsel, it sees a generic serial device, but it only allows me to choose arduino models, not the pico, so that's also not the way to go.
I've also tried 2 other picos and got the exact same error.
Any idea what could cause (and fix?) this? If there's any extra information I could give you that could be of use, ask away.

**Comment by sanjay900** [comment]
What OS? If your on Linux, then there are extra instructions to follow, they are linked in the guide but maybe I need to make them more obvious
https://github.com/sanjay900/guitar-configurator/issues/32

**Comment by sanjay900** [comment]
I intend to automate this process when the new config tool comes around,
but maybe I'll add a link to this within the tool itself or something for
Linux

**Comment by sanjay900** [comment]
Just added some more notes here:
https://sanjay900.github.io/guitar-configurator/guides/linux.html
if you plan on using ps3 mode and stuff, might want to follow the updated instructions in here.
